apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - repository.yaml
  - grafana-secret.yaml
  - grafana-nginx-config.yaml
  - grafana-tunnel.yaml
  - networkpolicies.yaml
  - dashboards
  - release.yaml
