apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - common-charts
  - metallb
  - longhorn
  - cert-manager
  - gateway-api
  - nginx-gateway-fabric
  - internal-dns
  - renovate
  - headlamp
  - onepassword
  - cloudnativepg
  - gatus
  - prometheus
  - trivy-operator
  - core-dns
