apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pi-hole
  - speedtest-tracker
  - flash-slothmore
  - hello-from-gondor
  - linkwarden
  - ollama
  - calibre-web-automated
  - homepage
  - foldingathome
