apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - calibre-web-automated
  - flash-slothmore
  - foldingathome
  - gwaihir
  - hello-from-gondor
  - homepage
  - linkwarden
  - ollama
  - pi-hole
  - smaug
  - speedtest-tracker
